### ISSUE TITLE
Using wp_remote_get instead of cURL

### ISSUE THREAD

**Issue by adamcapriola** [Patreon/patreon-php#10]
Hi David! Thanks for making all this code available. It's been super helpful for development.

I've got API requests working via cURL but I thought I'd also try using [`wp_remote_get`](https://codex.wordpress.org/Function_Reference/wp_remote_get) since native WordPress functions can be good for simplifying code. However, I am always getting a "403 Forbidden" response whenever I use the `wp_remote_get` method. Is there something special I'd need to do in order to get this working? Is an additional header or user agent needed?

_Example code:_

``` php
$access_token = 'xxxxxx';
$api_endpoint = 'https://api.patreon.com/oauth2/api/current_user';

$args = array(
    'headers' => array(
        'Authorization' => 'Bearer ' . $access_token
    )
);

$response = wp_remote_get( $api_endpoint, $args );

return $response;
```

**Comment by 21echoes** [comment]
hmmmm, there's no other headers required. I don't know enough about `wp_remote_get` to figure out why that code would fail. Our equivalent code is:

``php
$access_token = 'xxxxxx';
$api_endpoint = 'https://api.patreon.com/oauth2/api/current_user';
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $api_endpoint);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
$authorization_header = "Authorization: Bearer " . access_token;
curl_setopt($ch, CURLOPT_HTTPHEADER, array($authorization_header));
curl_exec($ch);
```

Try using the above code to see if it's just a `wp_remote_get` issue?

**Comment by adamcapriola** [comment]
Yeah, the above code is exactly what I've been using and it works great! I guess this is no real issue then. I'm simply curious why `wp_remote_get` is failing when it should be a reasonable alternative.

**Comment by 21echoes** [comment]
That's a good question.. This is not a wordpress plugin though, so I'd like to keep `wp_*` stuff out of the repo.

**Comment by spencerhandley** [comment]
@adamcapriola Circling back to this issue. The 403's that you were experiencing were a result of some overly aggressive filtering in our routing system which specifically targeted Wordpress. It should now work as expected.
