### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by graybay** [Patreon/patreon-php#13]
Basically I am trying to create a php script on my website that will access the list of my patrons and their pledge info, and then allow me to populate my own database with the relevant information.

I managed to get the individual user authentication working, but this isn't what I need. I would just like to use my own client credentials to fetch the info on all of my patrons. I've must have thoroughly read through the issues (https://github.com/Patreon/patreon-php/issues/2) at least 5 times now, but I still can't figure out how to get my Creator's Access Token working.

I'm probably missing something super obvious. I've tried most of the code snippets from the issues page, but without success. If someone could point me in the right direction, or give me an example script for this workflow I would be extremely grateful!

**Comment by graybay** [comment]
I've now managed to successfully use my Creator's Access Token to access my Patreon data, however I am now running into a few new issues that I just don't understand.

By using a for loop I can get a list of all the current pledge values for instance:
`foreach($pledges_page['data'] as $obj){
  print_r($obj['attributes']['amount_cents']);
 echo "<br/>";
}`

I can also get a list of pledges emails in the same way:
`foreach($pledges_page['included'] as $obj){
  echo $obj['attributes']['email']."<br/>";
 }`

This is about as far as I've gotten in finding any useful way to access this information. I've tried using the information 21echoes shared here [](https://github.com/Patreon/patreon-php/issues/8), but without luck.

What value is for %^$%^$%^$%

**Comment by 21echoes** [comment]
Hey @graybay ! So sorry I missed this when you first posted it. We use the [JSON-API standard](http://jsonapi.org/), which will probably a useful read so you understand our response formats. To jump into the meat of it, you'll want to do something like:

```
$user_id_map = [];
foreach($pledges_page['included'] as $obj) {
  if ($obj['type'] == 'user') {
    $user_id_map[$obj['id']] = $obj;
  }
}
foreach($pledges_page['data'] as $pledge_obj) {
  $user_id = $pledge_obj['relationships']['patron']['data']['id'];
  $user_obj = $user_id_map[$user_id];
  print_r($user_obj);
}```

Hopefully that helps!

**Comment by graybay** [comment]
Thanks @21echoes for getting back to me. Unfortunately I'm still having loads of trouble, I guess I'm completely in the dark when it comes to json. I resorted to parsing the manually generated csv to produce the following results for each patron:

Email Address: email@something.com
Pledge Amount: 5.00
Lifetime Pledged: 0.00
Payment Status: Ok

Would you be able to give me an example of how to print this same information using the patreon-php api? It would clear a lot up for me. Thanks so much!

**Comment by 21echoes** [comment]
https://github.com/Patreon/patreon-php/blob/master/examples/patron-list.php should be a great place to start! It prints the name and pledge amount of each patron.

**Comment by graybay** [comment]
@21echoes Thank you so much, this is a great start. I have a few more questions though.

`$patron_email = $user_id_map[$user_id]['attributes']['email'];`
Successfully gives me each patron's email address, however the first patron does not show an email address. This particular patron failed to pay, could this be related?

As for lifetime payments and current payment status, I've tried `['attributes']['patron_pays_fees'];` and `['attributes']['pledge_cap_cents'];` and neither of them give me anything. Is there a list of all possible attributes somewhere?

**Comment by 21echoes** [comment]
Right now, this `php` library does not support lifetime payments and current payment status :( The other libraries ([python](https://github.com/Patreon/patreon-python), [ruby](https://github.com/Patreon/patreon-ruby), [javascript](https://github.com/Patreon/patreon-js)) do, but we don't write any PHP at Patreon so this library tends to fall behind in functionality. We'll see if we can port over the custom fields code from the other libraries in the coming few months.

**Comment by graybay** [comment]
Oh well that explains it. Thank you for the swift replies. I will keep my eyes open for future updates.

**Comment by alromh87** [comment]
I could help implement missing features, but just can't find enough documentation as of how fields and include should be send, also what are the valid params
