### ISSUE TITLE
Initial Creator Access Token lifetime and scope + How to get per user processed amount of money

### ISSUE THREAD

**Issue by JayFoxRox** [Patreon/patreon-php#15]
This repo (those for other languages too) and the API documentation is in desperate need of more examples (and documentation).

---

My intention is to have a user authenticate on my website, the backend is then supposed to check if the user pledged a certain amount of money to my campaign last month. If the money was received / processed, the backend should provide certain functions which are not available otherwise.
Wether the server checks if the user is qualified through a reward (by having pledged enough for the month) or actually pledged enough for the month (without selecting the reward) doesn't really matter to me.

---

My current setup is like this: I have 2 OAuth Client API keys. One for the backend (used on the webserver) and another one for the client (also used on the webserver).

The client API keys are used to authenticate the user (get their `full_name` and `id`) so it has a limited scope. The backend API key is only used for the creator access token. However, I'm not sure if that token will expire in the future? If so, how would I update it? The token is currently hardcoded.
I've tried the `client_credentials` `grant_type` but it always gave `invalid_client` (despite it working with `authorization_code`).

I first thought that I could use the same API key for both kind of requests: using the creator token for campaign requests and a newly generated `access_token` from the `client_id` / `client_secret` for the user requests (with a limited scope). However, I noticed that generating an `access_token` for the client would also change the creator access token (which is then limited to 31 days and has the small scope?!). Generally the API is unclear wether "your" and "my" information is related to the creator who owns the API key or the user who logged in with said API key.
(Recommendation: Show the scope and when the token will expire on the API Key page where it is first generated? Be more clear what scope is necessary and wether the data is about key owner or key user)

So after I went through the trouble and figuring out that I need 2 Client API keys, I've looked at the actual data and had a hard time understanding the returned data: The API only seems to tell me the current pledge, not the actual value / money which was processed last month. Also I can't find the information wether the payment actually went through or wether there were problems.

---

Maybe someone could explain how this should be done correctly?

Also, is there a central place where this kind of question can be answered (IRC / Discord / Forum about the Patreon API) ?
This isn't really PHP API specific so I feel really bad for asking here. Also it probably hides a lot of useful answers in wrong places.

**Comment by 21echoes** [comment]
Hey @JayFoxRox !

1. As these libraries are currently in secret beta, we don't have the resources to really add more documentation. We will be investing more in platform in the coming years, but sadly right now we can't afford to.
2. I'd love understand why you think you need two OAuth clients? That definitely should not be needed.
3. We strongly encourage you to use our Charge Up-Front feature if you want to guarantee that patrons have paid before distributing content/access/etc. Checking history of past payments without Charge Up-Front makes your patrons wait up to 30 days to be "real" patrons, which decreases their satisfaction and your revenue.

**Comment by JayFoxRox** [comment]
@21echoes 

**Re 1**: okay

**Re 2**: Like my post explains:

I have 2 scopes I want to use. I don't want to ask too much information of the user who wants to authenticate via oauth, so I decide to use a "user" scope here. Using that information the backend knows who the user is, but can't access most of their information (which is a good thing!).
(As the user authenticates using the standard `authorization_code`, they also kick it off using the Patreon auth frontend)

At that point the backend should itself check in my campaign (= the creator campaign of the API keys the oauth used) wether the user paid (or at least pledged). Obviously this needs a somewhat wider scope to access my (not users) campaign information. Also, this time there is no user present to kick off the authorization and I don't feel like logging my server into my personal account (by faking responses to the auth frontend).
The standard oauth way of handling this would probably be the `client_credentials` which would grant access using the `client_id` and `client_secret` without additional user information. The scope of that would probably be full access to my profile / campaign. However, I keep getting `invalid_client` as a response.

As a temporary solution I've created a second API key for the backend which never does `authorization_code` as that would change the `access_token`. However, I feat that the `access_token` from the API key page will expire soon and I don't know when.
I can't use the first API key for this purpose as its creator `access_token` keeps changing when a user authenticates using `authorization_code`. As such I can not hardcode it + the scope would depend on what the user sends in their auth request (which they might have tampered with).

**Re 3**: I have not heard / read about this feature yet (or I don't remember). I'll check what I have configured

**Comment by 21echoes** [comment]
Am I understanding, then, that you have made two clients only because you want the client to which the patrons authenticate to have more limited scopes? If so, no need to worry -- we already tightly scope all clients you make, so that you can only access information that you, the creator, could already access on patreon.com today. No additional information is granted by users authenticating with any scope that you couldn't already gather from looking at your Patron Manager.

Regarding expiration: we can definitely add an "expires at" date to the documentation. Additionally, every time you request a token, we send back an `expires_in` value that tells you when the new token will expire.

It also sounds like you're saying that requesting tokens with client 1 affects client 2's tokens? Trying that myself (and looking at our token rotation code), I can't see how that'd be the case. Either I've misunderstood what you've written, or you're mixing up your clients somehow, or.. ??? My bet is the former, but definitely want to double check here :D 

Anyway, hope this helps! You've also inspired me to open source our internal testing instance for this stuff sooner rather than later, so people can use it as an example of ideal usage patterns. It won't be in PHP, but I'll post it here once it goes up (hopefully before the end of next week, when the holidays begin)

**Comment by 21echoes** [comment]
We've put up a demo app here: https://github.com/Patreon/patreon-ruby/tree/master/example/sinatra Let me know if that helps! or any other example usages you'd like to see
