### ISSUE TITLE
Example for webhooks / HMAC 

### ISSUE THREAD

**Issue by fabd** [Patreon/patreon-php#20]
It would be very helpful to have an php example of answering to a webhook, along with a library from github that would handle the HMAC stuff.

It sounds like we have to encode the request paameters and the client secret perhaps into some kind of signature and compare it with the HMAc in the header? I have no idea where to even start.

**Comment by hopstudios-jeslen** [comment]
I can't even get the form to submit without the error 'Parameter 'id' is missing.' on the webhooks page https://www.patreon.com/platform/documentation/webhooks

**Comment by sabrehagen** [comment]
I'm getting this too. Here's a screenshot:

![id issue](http://i.imgur.com/EZeU4rs.png)

 Updating the docs with the correct format would be helpful. Also [this](https://patreon.zendesk.com/hc/en-us/articles/206525646-Does-Patreon-have-an-API-) is the top result in Google when searching 'patreon api'. Only through this issue did I find your [documentation](https://www.patreon.com/platform/documentation/overview) page. I'd suggest adding a link to your documentation on the zendesk support article given it's SEO friendliness.

**Comment by jamiemac262** [comment]
I had the same issue with "Parameter 'id' is missing" but only when trying to add a second and 3rd web hook. Refreshing the page helped.

I would also like to see an example of the information sent from each of the webhooks. Currently, the best way I can think of to get information about what each webhook sends is to dump the $_server into a text file for each event. I'm in the process of... learning how to do that now haha

**Comment by jamiemac262** [comment]
Hey guys, This is what var_dump($_SERVER) looks like when you hit the "Test" button for a create event

`array(36) {
  ["PATH"]=>
  string(180) "/usr/local/jdk/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/X11R6/bin:/usr/local/bin:/usr/X11R6/bin:/root/bin:/opt/bin"
  ["SCRIPT_NAME"]=>
  string(35) "/classes/patreon/pledges/create.php"
  ["REQUEST_URI"]=>
  string(35) "/classes/patreon/pledges/create.php"
  ["QUERY_STRING"]=>
  string(0) ""
  ["REQUEST_METHOD"]=>
  string(4) "POST"
  ["SERVER_PROTOCOL"]=>
  string(8) "HTTP/1.1"
  ["GATEWAY_INTERFACE"]=>
  string(7) "CGI/1.1"
  ["REMOTE_PORT"]=>
  string(5) "31299"
  ["SCRIPT_FILENAME"]=>
  string(61) "/home/gamerfin/public_html/classes/patreon/pledges/create.php"
  ["SERVER_ADMIN"]=>
  string(25) "webmaster@gamerfinder.net"
  ["CONTEXT_DOCUMENT_ROOT"]=>
  string(26) "/home/gamerfin/public_html"
  ["CONTEXT_PREFIX"]=>
  string(0) ""
  ["REQUEST_SCHEME"]=>
  string(4) "http"
  ["DOCUMENT_ROOT"]=>
  string(26) "/home/gamerfin/public_html"
  ["REMOTE_ADDR"]=>
  string(12) "52.53.186.77"
  ["SERVER_PORT"]=>
  string(2) "80"
  ["SERVER_ADDR"]=>
  string(14) "149.255.60.167"
  ["SERVER_NAME"]=>
  string(15) "gamerfinder.net"
  ["SERVER_SOFTWARE"]=>
  string(6) "Apache"
  ["SERVER_SIGNATURE"]=>
  string(0) ""
  ["LD_LIBRARY_PATH"]=>
  string(21) "/usr/local/apache/lib"
  ["CONTENT_LENGTH"]=>
  string(5) "32394"
  ["CONTENT_TYPE"]=>
  string(16) "application/json"
  ["HTTP_X_PATREON_SIGNATURE"]=>
  string(32) "8e49529a5766deb5b10d778ec0bc1284"
  ["HTTP_X_PATREON_EVENT"]=>
  string(14) "pledges:create"
  ["HTTP_CONNECTION"]=>
  string(5) "close"
  ["HTTP_ACCEPT"]=>
  string(3) "*/*"
  ["HTTP_ACCEPT_ENCODING"]=>
  string(13) "gzip, deflate"
  ["HTTP_USER_AGENT"]=>
  string(60) "python-requests/2.5.2 CPython/3.6.2 Linux/3.13.0-128-generic"
  ["HTTP_HOST"]=>
  string(15) "gamerfinder.net"
  ["UNIQUE_ID"]=>
  string(24) "WZ2OlpX-PKcAAGWxW5IAAAAG"
  ["TZ"]=>
  string(13) "Europe/London"
  ["FCGI_ROLE"]=>
  string(9) "RESPONDER"
  ["PHP_SELF"]=>
  string(35) "/classes/patreon/pledges/create.php"
  ["REQUEST_TIME_FLOAT"]=>
  float(1503497878.4841)
  ["REQUEST_TIME"]=>
  int(1503497878)
}`

Yeh, so the documentation is lacking a little here. because I have no idea how to get any useful information out of any of this. no patron ID, pledge information, nothing :/

**Comment by jamiemac262** [comment]
I've solved the original issue I think.

the event data is being sent in the POST request body. In PHP we can access this information like so:

`$input = @file_get_contents("php://input");
$event_json = json_decode($input);`

once you have run that snippet of code, your event can be found in `$event_json`.

As the browser never navigates to these PHP files, it is a good idea to write all your output to files

For example, My "create.php" file looks like this:

```
$input = @file_get_contents("php://input");
$event_json = json_decode($input);

ob_flush();
ob_start();

	var_dump($event_json);

file_put_contents("post.txt", ob_get_flush());
```

hat you get in the signature is just there to let you verify the POST response body hasn't been tampered with/intercepted. I don't know anything about HMAC-MD5 so I'm not going to try and explain it here :P 

I hope this has helped you guys :) 

lastly... Patreon!! can we please see this^^^ in the Documentation!? haha (this is 4 hours of my life I'm not getting back)


I believe you now have the basic information you need to understand how this works :)

**Comment by ehippy** [comment]
Here's a nodeJS working example of how to check the hash on the POST:

``` js
    let crypto = require('crypto');

    let hash = event.headers['X-Patreon-Signature'],
        hmac = crypto.createHmac("md5", 'secret_here'); //use your patreon secret here

    hmac.update(event.body);

    let crypted = hmac.digest("hex");

    if (crypted === hash) {
        console.log("That's good hash! " + hash);
    } else {
        console.log("Bad hash! " + hash + " crypted " + crypted);
    }
```

Cheers.

**Comment by SteveWhitby** [comment]
Hi all
I have a fully working webhooks page using php and mysqli hope this helps

mysql DB tables required for my implimentation

/**
--
-- Table structure for table `patrons`
--
CREATE TABLE IF NOT EXISTS `patrons` (
`patron_key` bigint(20) NOT NULL AUTO_INCREMENT COMMENT 'key to row',
`patron_id` tinytext NOT NULL COMMENT 'patron id',
`patron_fullname` tinytext NOT NULL COMMENT 'fullname',
`patron_firstname` tinytext NOT NULL,
`patron_lastname` tinytext NOT NULL,
`patron_email` tinytext NOT NULL,
`patron_image_url` tinytext NOT NULL,
`patron_pledge` bigint(20) NOT NULL,
`patron_list` tinyint(4) NOT NULL COMMENT 'include in patrons honour list',
`patron_decline` tinytext,
PRIMARY KEY (`patron_key`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--
-- Table structure for table `notifications`
--

CREATE TABLE IF NOT EXISTS `notifications` (
  `notification_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `notification_type` tinytext NOT NULL,
  `notification` text NOT NULL,
  `notification_action` int(11) NOT NULL,
  `notification_date` tinytext NOT NULL,
  `notification_archived` tinytext NOT NULL,
  PRIMARY KEY (`notification_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1401 ;

*/

$secret_webhook_id = "your-secret-key-here";

/** get the headers */
$headers             = getallheaders();
$X_Patreon_Event     = $headers['X-Patreon-Event'];
$X_Patreon_Signature = $headers['X-Patreon-Signature'];

/** get the json body */
$body                = @file_get_contents("php://input");

/** get json body as array */
$patron_data         = json_decode($body, true);

/** compute an md5 hash using the body and your secret key */
$signature           = hash_hmac('md5', $body, $secret_webhook_id);

/** Timing attack safe string comparison */
if (hash_equals ($X_Patreon_Signature, $signature)){

    /** get the data from the json array - look for errors*/
    if (isset($patron_data['included']) && isset($patron_data['data'])) {
        $data             = $patron_data['data'];
        $declined         = $data['attributes']['declined_since'];

        /** stored as a string*/
        $declined         = is_null($declined) ? "":$declined;

        $included         = $patron_data['included'];
        $patron_id        = $included[0]['id'];
        $patron_full_name = $included[0]['attributes']['full_name'];
        $patron_firstname = $included[0]['attributes']['first_name'];
        $patron_lastname  = $included[0]['attributes']['last_name'];
        $patron_email     = $included[0]['attributes']['email'];
        $patron_image_url = $included[0]['attributes']['image_url'];
        $pledge           = $included[1]['attributes']['amount_cents'];

        /** select event for db insert/update/delete*/
        switch ($X_Patreon_Event){
            case "pledges:create":
                $sql = "INSERT INTO patrons SET patron_id  = ?, patron_fullname = ?, patron_firstname = ?, patron_lastname = ?, patron_email = ?, patron_image_url = ?, patron_pledge = ?, patron_list = 1, patron_decline = ?";
                $stmt = $conn->prepare($sql);
                $stmt->bind_param("ssssssis", $patron_id, $patron_full_name, $patron_firstname, $patron_lastname, $patron_email, $patron_image_url, $pledge, $declined);
                if (!$stmt->execute()) {
                    /** your_error_routine(__LINE__, __FILE__, $sql, $stmt->error); */
                }
                break;
            case "pledges:update":
                $sql = "UPDATE patrons SET patron_fullname = ?, patron_firstname = ?, patron_lastname = ?, patron_email = ?, patron_image_url = ?, patron_pledge = ?, patron_decline = ? WHERE patron_id = ?";
                $stmt = $conn->prepare($sql);
                $stmt->bind_param("sssssiss", $patron_full_name, $patron_firstname, $patron_lastname, $patron_email, $patron_image_url, $pledge, $declined, $patron_id);
                if (!$stmt->execute()) {
                    /** your_error_routine(__LINE__, __FILE__, $sql, $stmt->error); */
                }
                break;
            case "pledges:delete":
                $sql = "DELETE FROM patrons WHERE patron_id = ?";
                $stmt = $conn->prepare($sql);
                $stmt->bind_param("s", $patron_id);
                if (!$stmt->execute()) {
                     /** your_error_routine(__LINE__, __FILE__, $sql, $stmt->error); */
                }
                break;
        }

        /** now update your own admin notifications */
        $notification = "Patreon Webhook update for: $patron_full_name - X_Patreon_Event: $X_Patreon_Event";
        $sql = "INSERT INTO notifications SET notification_type = 'Patreon', notification = ?, notification_date = ".time();
        $stmt = $conn->prepare($sql);
        $stmt->bind_param("s", $notification);
        if (!$stmt->execute()) {
            /** your_error_routine(__LINE__, __FILE__, $sql, $stmt->error); */
        }
    }
}

**Comment by RubyTheRose** [comment]
> I've solved the original issue I think.
> 
> the event data is being sent in the POST request body. In PHP we can access this information like so:
> 
> `$input = @file_get_contents("php://input"); $event_json = json_decode($input);`
> 
> once you have run that snippet of code, your event can be found in `$event_json`.
> 
> As the browser never navigates to these PHP files, it is a good idea to write all your output to files
> 
> For example, My "create.php" file looks like this:
> 
> ```
> $input = @file_get_contents("php://input");
> $event_json = json_decode($input);
> 
> ob_flush();
> ob_start();
> 
> 	var_dump($event_json);
> 
> file_put_contents("post.txt", ob_get_flush());
> ```
> hat you get in the signature is just there to let you verify the POST response body hasn't been tampered with/intercepted. I don't know anything about HMAC-MD5 so I'm not going to try and explain it here :P
> 
> I hope this has helped you guys :)
> 
> lastly... Patreon!! can we please see this^^^ in the Documentation!? haha (this is 4 hours of my life I'm not getting back)
> 
> I believe you now have the basic information you need to understand how this works :)

Regarding this, I've tried doing this myself and in my file, all it says is NULL. I'm still confused on how I'm supposed to obtain the patreon information.

**Comment by jrsun** [comment]
Have you [created a webhook on Patreon](https://www.patreon.com/portal/registration/register-webhooks) and pointed it at your URL? Can you elaborate on what's getting returned as NULL?

**Comment by RubyTheRose** [comment]
@jrsun Of course I've created a web hook, how else would I be sending the test data?

**Comment by clarkmu** [comment]
In case anyone else is having issues on NodeJS, I had to add the last line of this snippet:

let data = req.body;
const hash = crypto
  .createHmac("md5", PATREON_API_SECRET)
   .update(data)
  .digest("hex");

data = JSON.parse(data.toString());
