### ISSUE TITLE
README.md example doesn't work: I get MY (creator) profile, and no "included" section

### ISSUE THREAD

**Issue by fabd** [Patreon/patreon-php#21]
Nevermind found the problem.

**Comment by BarryCarlyon** [comment]
What was the solution?

**Comment by fabd** [comment]
Sorry it's been a while. It was completely unintuitive to me.

If you want a list of patrons it's not in the README.md , see the examples folder.

I'd suggest to copy the auth codes somewhere for use in other API calls, while you are debugging / figuring this stuff. Then you make the calls to get the data, and you `print_r`the results.. then you'll see how you connect creator ids and things like that to get the data you want in a completely unintuitive way. Pretty much all the data is upside down.
