### ISSUE TITLE
Fetching and displaying campaign data via API

### ISSUE THREAD

**Issue by daniellieske** [Patreon/patreon-php#22]
I'd like to use the patreon.php to get the current funding level (total pledge amount) of my Patreon campaign and display this info on my website. I hope it's not too much to ask for a code snippet that does exactly that.

Thanks for your efforts!

-DanieL

**Comment by 21echoes** [comment]
I've taken [our patron list example](https://github.com/Patreon/patreon-php/blob/master/examples/patron-list.php) and modified it to show how to read the data you want from the `$campaign_response`:

```php
<?php

require_once('vendor/patreon/patreon/src/patreon.php');
use Patreon\API;
use Patreon\OAuth;

// Get your current "Creator's Access Token" from https://www.patreon.com/platform/documentation/clients
$access_token = null;
// Get your "Creator's Refesh Token" from https://www.patreon.com/platform/documentation/clients
$refresh_token = null;
$api_client = new Patreon\API($access_token);

// Get your campaign data
$campaign_response = $api_client->fetch_campaign();
// If the token doesn't work, get a newer one
if ($campaign_response['errors']) {
    // Make an OAuth client
    // Get your Client ID and Secret from https://www.patreon.com/platform/documentation/clients
    $client_id = null;
    $client_secret = null;
    $oauth_client = new Patreon\OAuth($client_id, $client_secret);
    // Get a fresher access token
    $tokens = $oauth_client->refresh_token($refresh_token, null);
    if ($tokens['access_token']) {
        $access_token = $tokens['access_token'];
        echo "Got a new access_token! Please overwrite the old one in this script with: " . $access_token . " and try again.";
    } else {
        echo "Can't recover from access failure\n";
        print_r($tokens);
    }
    return;
}

// get the fields you want
$campaign_attributes = $campaign_response['data'][0]['attributes'];
$campaign_pledge_sum = $campaign_attributes['pledge_sum'];
```

**Comment by daniellieske** [comment]
Thank you for providing me an example for my specific case! 

It works fine as long as the access token and refresh token are valid. However, I noticed that these tokens are renewed every month and currently I have to manually update the script in order to make it work which is not an ideal solution because I want to display the state of my Patreon campaign permanently on the homepage of my website. So I'm looking for a way to automatically receive the most recent access token and refresh token. 

If I understand it right, in order to receive updated tokens I would have to initiate an OAuth request using my client ID and client secret. I know the process from a Patreon Login button which is also running on my website. In that case you need to visit the Patreon website, confirm the OAuth request, and return to your website with the needed variables in the URL. Is this something that you can be done in the background for the functionality that I'm looking for? Is there by any chance an easier way to receive the access token and refresh token in order to make a permanent display of API-fetched information on a website work?

**Comment by 21echoes** [comment]
the following piece of code from my original response handles refreshing tokens for you, without any visit to patreon.com:
```// If the token doesn't work, get a newer one
if ($campaign_response['errors']) {
    // Make an OAuth client
    // Get your Client ID and Secret from https://www.patreon.com/platform/documentation/clients
    $client_id = null;
    $client_secret = null;
    $oauth_client = new Patreon\OAuth($client_id, $client_secret);
    // Get a fresher access token
    $tokens = $oauth_client->refresh_token($refresh_token, null);
    if ($tokens['access_token']) {
        $access_token = $tokens['access_token'];
        echo "Got a new access_token! Please overwrite the old one in this script with: " . $access_token . " and try again.";
    } else {
        echo "Can't recover from access failure\n";
        print_r($tokens);
    }
    return;
}```

Right now, it prints out "Got a new access_token! Please overwrite the old one in this script with: <new access token> and try again.". If, rather than editing the script by hand, you want to handle this dynamically, you should be storing your tokens in a dynamic place (say, a `.json` file on disk that you can read from / write to, or a database if you have one set up), so that the script can write to that location rather than having you update the script by hand.

**Comment by daniellieske** [comment]
All right, thanks for pushing me into the right direction. Requesting new tokens now works with the code you've provided. I write the provided tokens into a textfile and fetch them from there. Thank you very  much!
