### ISSUE TITLE
Log In with Patreon not returning results

### ISSUE THREAD

**Issue by SonnyCrockett** [Patreon/patreon-php#24]
Apologies if I'm missing something obvious, but I'm trying to allow my users to log in via Patreon so I can give them access to certain parts of my site.

I have followed the instructions here...
https://www.patreon.com/platform/documentation/oauth

...and can get up to Step 3 before things start to go awry.

**Step 0:** ✅ 
I registered my client application and am in possession of my **Client ID** and **Client Secret** (as well as my **Creator's Access Token** and **Creator's Refresh Token**). I have also set my Redirect URI on this page. 

**Step 1:** ✅
I made the login button on my site and it looks like this
```
<a href="https://www.patreon.com/oauth2/authorize?response_type=code&client_id=9c1...c9&redirect_uri=http://mysite.local/members/archive">Log in via Patreon</a>
```

I can successfully click this link and be taken to the Patreon Login asking my permission to grant mysite access to my information.

**Step 2:** ✅
When I click 'Allow' I am redirected back to my redirect_uri as expected. The URL includes the expected args: `?code=s6pK...aOGjG&state=None`

**Step 3:** 😡
For this step I am using the plugin found here...
https://github.com/Patreon/patreon-php
...swapping out **$client_id**, **$client_secret** and **$creator_id** with my unique values as instructed.

However, this is the point where I am getting stuck. I'm not seeing any data being returned. In troubleshooting this, as instructed in [another Issue found here](https://github.com/Patreon/patreon-php/issues/2#issuecomment-225311677), I've added...
```
$oauth_grant_code = $_GET["code"]; // or request_var("code", "ERROR: NO CODE");
 echo "oauth_grant_code = ",$oauth_grant_code,"<br/>";
```

Unlike those guys, I *AM* seeing a value being returned for that `oauth_grant_code` (it's the same as the `?code=` value being returned in my redirect uri. But in trying to echo out other vars, I get nothing...
```
oauth_grant_code = s6pK...aOGjG
tokens = 
access_token = 
patron_response = 
patron = 
```

I've double-checked to make sure my path is correct in the `require_once` pointing to `patreon.php` at the top of the page. I can successfully add test echos in `patreon.php`, `API.php` and `OAuth.php` which tells me that everything should be set up correctly to take in my `oauth_grant_code` and spit out the tokens and responses those API and OAuth files should be generating. No?

Again, my apologies if I'm missing something obvious. I'm not a back-end dev, but from what I can tell this should be working. Any assistance would be greatly appreciated!

**Comment by SonnyCrockett** [comment]
**UPDATE**
I am still not able to get this working locally. However, I did push my code up to a dev server that I use for testing alongside my main domain and am seeing some results returning.

Specifically, the `access_token` and `refresh_token` are coming back and being populated now. Furthermore, I can see my own bio info and whatnot. 

What I am NOT able to see, however, is any sort of list of patrons. I don't think `included` is being populated because it doesn't appear this `if/foreach` is running:
```
if ($included != null) {
  foreach ($included as $obj) {
    if ($obj["type"] == "pledge" && $obj["relationships"]["creator"]["data"]["id"] == $creator_id) {
      $pledge = $obj;
      break;
    }
  }
}
```

Finally, if I try to echo out `included` using `echo 'included = ', print_r($included;` it does return a value of `1`. Not sure if that helps or means anything.

(And I'd still like to get this working locally if anyone has any ideas. Having to push code up to the dev server to see changes is cumbersome). Thanks!

**Comment by BarryCarlyon** [comment]
I'm seeing the same.

A call to `$patron_response = $api_client->fetch_user();` is not returning whom I (logged in user) pledge to in the response either.

**Comment by BarryCarlyon** [comment]
I did some testing.

fetch_user doesn't return included, becuase I don't pledge to myself.

You need to use a clientID and secret of the campaign you want to get data for. So I borrowed the ID of someone I do pledge to (with their permission) and now I have a included key.

The docs are jsut not clear on the subject.

included is returned when the authenticating user, is pledged to the person that ClientID belongs to.

So if the person had more than one campaign, and authenticating users pledges to them all you'd get more included's

**Comment by 21echoes** [comment]
@SonnyCrockett -- It is likely not working on your local server because that server's `redirect_uri` does not match the `redirect_uri`s you listed when you created your API client. OAuth's security model requires whitelisting exactly the servers which you want to have rights to use of your client ID and secret, so any mismatching `redirect_uri` is going to fail permission checks. You can always inspect the response status code and body to confirm you're getting something other than an http 200 and a helpful error in the response body.

@BarryCarlyon (and @SonnyCrockett 's second issue) -- Pledges can only be returned if there is a pledge to return. If you "Log in with Patreon" as a user who is not pledging to the campaign which owns the OAuth Client, then there won't be any pledges to include, so you should expect that `included` array to be empty (and for the `relationships` key on the returned user under `data` to indicate there is no related pledge). You should make sure you code your server to handle both users who are patrons and users who are not patrons.

**Comment by SonnyCrockett** [comment]
@21echoes makes sense about the `included` stuff. I am the creator of my campaign which would explain why I get nothing in this area. I think more than anything, I just wanted to make sure that was the case. Now that I know not to fret over it, I think I have this working properly on my dev server. The next step for me appears to be incorporating the user data that comes from this API into my site's db so that I can gate access to certain things. That should be a wild ride.

As far as getting this running on my local, I did indeed have the correct `redirect_uri` listed in my API Client. Definitely not mismatched. I will check to see if I'm getting anything in the response status code as you mentioned. Maybe something is going on behind the scenes that I'm not aware of? We shall see.

Thanks for the feedback!

**Comment by 21echoes** [comment]
Awesome! Feel free to email us directly at platform@patreon.com if you want more hands-on help with debugging the `redirect_uri` issue :D

**Comment by 21echoes** [comment]
Oh and sadly we do not have any sandbox / mimic data system yet, but we're definitely looking to build it sometime soon.
