### ISSUE TITLE
OAuth's refresh_token Method Does Not Work

### ISSUE THREAD

**Issue by IridescentShadow** [Patreon/patreon-php#25]
I've implemented code on my site based on the example you posted [here](https://github.com/Patreon/patreon-php/blob/master/examples/patron-list.php).

When I call $oauth_client->refresh_token($refresh_token,null), I get the following response:

`Can't recover from access failure.
Array (
    [error] => invalid_grant
)`

This causes my script to fail every time the access tokens change (monthly) until I manually go into the [Clients & API Keys](https://www.patreon.com/platform/documentation/clients) page to copy/paste the new keys into my script.

**Comment by daniellieske** [comment]
I'd just like to second this Issue because I'm also looking for a way to permanently display API-fetched information on my website without having to manually update the access token and refresh token in my script.

**Comment by IridescentShadow** [comment]
@daniellieske Based on their lack of feedback, I ended up just using the Patron list export to CSV and then writing an importer using PHPExcel. I'd be happy to share that code if you're still looking for a solution

**Comment by JoshuaMckendall** [comment]
Are you manually pasting the access and refresh tokens into the script? Why not store it in a database column or something, then just update those columns?

```
require_once('vendor/patreon/patreon/src/patreon.php');
use Patreon\API;
use Patreon\OAuth;

// Create a database table named client and the appropriate columns: client_id, client_secret, access_token  etc...
// Place your client id within the script (as well as the corresponding row and db column)
$client_id = 'YOUR CLIENT ID';

try {

  // CHOOSE A DATABASE I USED SQLite HERE
  // SQLite Database
  $dbh = new PDO("sqlite:my/database/path/database.db");

  $dbh->setFetchMode(PDO::FETCH_ASSOC);

  $statement = $dbh->prepare("SELECT client_id, client_secret, access_token, refresh_token FROM client WHERE client_id = ?");

  $statement->execute($client_id);

  $result = $statement->fetch();
}
catch(PDOException $e) {

    echo $e->getMessage();

}

// Get your current "Creator's Access Token" from https://www.patreon.com/platform/documentation/clients
$access_token = $result['access_token']; 

// Get your "Creator's Refesh Token" from https://www.patreon.com/platform/documentation/clients
$refresh_token = $result['refresh_token'];

$api_client = new Patreon\API($access_token);

// Get your campaign data
$campaign_response = $api_client->fetch_campaign();

// If the token doesn't work, get a newer one
if ($campaign_response['errors']) {

    // Make an OAuth client
    // Get your Client ID and Secret from https://www.patreon.com/platform/documentation/clients
    $client_id = $result['client_id'];

    $client_secret = $result['client_secret'];

    $oauth_client = new Patreon\OAuth($client_id, $client_secret);

    // Get a fresher access token
    $tokens = $oauth_client->refresh_token($refresh_token, null);

    if ($tokens['access_token']) {

		$statement = $dbh->prepare("UPDATE client ( access_token, refresh_token ) values ( :access_token, :refresh_token )");

		$statement->bindParam(':access_token', $access_token);

		$statement->bindParam(':refresh_token', $refresh_token);

		$access_token = $tokens['access_token'];

		$refresh_token = $tokens['refresh_token'];

		$statement->execute();


        echo "Got a new access_token!";

    } else {

        echo "Can't recover from access failure\n";

        print_r($tokens);

    }

    return;
}

```

**Comment by JoshuaMckendall** [comment]
P.S. I'm mainly responding to @daniellieske after seeing #22

**Comment by daniellieske** [comment]
**@ JM:**

Well, it doesn't make that big of a difference if I copy & paste the new token into a database or directly into my script.

**@21echoes:**

I'm not a coder but I think the basic problem here is that the `refresh_token` method is part of the OAuth flow and thus requires a manually confirmed URL redirect to the Patreon website in order to fetch the access key. The information I want to display on my website, every time it is loaded, is simple information from my own Patreon campaign (pledge level, number of Patrons, ...) and I currently access it via a simple API call like you provided in on of your examples:

```
$api_client = new Patreon\API( $access_token );
// Get your campaign data
$campaign_response = $api_client->fetch_campaign();
```
That works very well, but currently `$access_token` is hard coded in my script because I haven't found a way to request my access token via the API. And I can't use the OAuth flow because it requires the redirect to the Patreon website and the manual confirmation process which simply doesn't work for information that is meant to be displayed and updated every time a user loads my website.

To put it in a nutshell:

What I need is

**a way to fetch my current access token via a simple API call that does not involve OAuth.** 

OR

**a way to make an API call only with my client ID and client secret because those do not change every 30 days.**

Thanks for providing an additional contact address. I'll try to forward the discussion to that address.

**Comment by JoshuaMckendall** [comment]
@daniellieske 

I don't know how familiar you are with php and coding in general, but you do realize that the hard coded values within your script never change right? It will always use the hard coded value. So what I was proposing in the script I pasted was that you input all of your info (client_id, client_secret, access_token, refresh_token) into a database, then have the **_script_** update that row in the database when your access_token expires. then your script will pull the new info from your database. 

> I think the basic problem here is that the refresh_token method is part of the OAuth flow and thus requires a manually confirmed URL redirect to the Patreon website in order to fetch the access key.

The OAUTH client already does an asynchronous cURL request to get a new access_token without redirecting to the patreon website.

```
 $oauth_client = new Patreon\OAuth($client_id, $client_secret);

    // Get a fresher access token
    $tokens = $oauth_client->refresh_token($refresh_token, null);
```

It's just a matter of saving that new access_token somewhere (like in a database)


From Patreon\OAuth (__update_token makes an OAuth request to the API without redirecting)

```
public function refresh_token($refresh_token, $redirect_uri) {
    return $this->__update_token(array(
        "grant_type" => "refresh_token",
        "refresh_token" => $refresh_token,
        "client_id" => $this->client_id,
        "client_secret" => $this->client_secret
    ));
  }
  private function __update_token($params) {
    $api_endpoint = "https://api.patreon.com/oauth2/token";
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, $api_endpoint);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($params));
    return json_decode(curl_exec($ch), true);
  }
}
```

**Comment by daniellieske** [comment]
@JoshuaMckendall:

Thanks for explaining your approach in more detail. I guess the big problem is that I don't get this code to work properly:

```
 $oauth_client = new Patreon\OAuth($client_id, $client_secret);

    // Get a fresher access token
    $tokens = $oauth_client->refresh_token($refresh_token, null);
```
In my case it doesn't seem to return a valid access token. If I'm using that code and try to output `$tokens` for example with `echo $tokens;` there's nothing. In fact I'm getting an error message that says:

`Parse error: syntax error, unexpected '$tokens' (T_VARIABLE)` 

And IF this code worked, I actually don't quiet get why I should store the variable in a database. Wouldn't it be possible to request the access token every time my script is loaded?

Maybe I'm making some very stupid mistake here, I'm really not that good in coding and might overlook even very basic stuff...

**Comment by daniellieske** [comment]
Ok, I'm coming closer I guess. If you use the refresh_token method and then:

`print_r($tokens);`

At least I'm getting something back:

`Array ( [error] => invalid_client )`

And thus we're back at IridescentShadow 's original problem at the beginning of this thread.

**Comment by daniellieske** [comment]
I'm starting to suspect that the problem lies in the fact that I'm also having a Patreon Login installed at my website, which is using a different client (with different credentials) and since I'm including the same patreon.php for my API call, I'm not doing the refresh_token request with the right client credentials (as they are centrally stored in the patreon.php).

**Comment by 21echoes** [comment]
Hey @daniellieske ! Your visitors will not need to visit Patreon.com if youre only using your own access token, rather than requesting new tokens on your visitor's behalf. In other words: this should work for your use case just fine. If you could reach out directly to platform@patreon.com, we can help you debug the `Array ( [error] => invalid_client )` error in more detail 👍

**Comment by daniellieske** [comment]
I'd like to add that I was finally able to make it work. This is the code I'm using:

```
require_once( "inc/libs/patreon/api.php" );
require_once( "inc/libs/patreon/oauth.php" );

use Patreon\API;
use Patreon\OAuth;

//Get initial set of Tokens from https://www.patreon.com/platform/documentation/clients

//Save Access Token in text file "accesstoken.txt" and Refresh Token in "refreshtoken.txt"

//Reading the current tokens from the text files
$accesstokenfile = fopen("inc/accesstoken.txt", "r");
$access_token = fread($accesstokenfile, filesize("inc/accesstoken.txt"));
fclose($accesstokenfile);

$refreshtokenfile = fopen("inc/refreshtoken.txt", "r");
$refresh_token = fread($refreshtokenfile, filesize("inc/refreshtoken.txt"));
fclose($refreshtokenfile);

//New API call
$api_client = new Patreon\API( $access_token );

// Get your campaign data
$campaign_response = $api_client->fetch_campaign();

// If the campaign data can't be fetched because the Access Tokens is expired we request new tokens using our client ID and client secret
if ($campaign_response['errors']) {
	$client_id = "YOUR_CLIENT_ID";
	$client_secret = "YOUR_CLIENT_SECRET";
	$oauth_client = new Patreon\OAuth($client_id, $client_secret);
	$tokens = $oauth_client->refresh_token($refresh_token, null);

//We load the new tokens into new variables...
	$newaccess_token = $tokens['access_token'];
	$newrefresh_token = $tokens['refresh_token'];

//... and overwrite our text files with the new info
	$file = fopen("inc/accesstoken.txt", "w");
	$content = $newaccess_token;
	fwrite($file, $content);
	fclose($file);

	$file = fopen("inc/refreshtoken.txt", "w");
	$content = $newrefresh_token;
	fwrite($file, $content);
	fclose($file);

//We make a new API call with the new tokens	
	$api_client = new Patreon\API( $newaccess_token );
	$campaign_response = $api_client->fetch_campaign();
	}

//Now we have our campaign data and can disply e.g. the number of our Patrons
$patrons = $campaign_response["data"][0]["attributes"]["patron_count"];
```
This code takes the Tokens from the text files and only gets new ones when one of the tokens (typically the Access Token, as it is refreshed on Patreon's side every 30 days) fails. 

This probably isn't very elegant code (and the txt.-files can be accessed from outsiders although I don't think that this is a big problem) but I'm a comic artist and I'm proud as hell that I made it work with everyone's help. :)

**Comment by LiamDawe** [comment]
Just thought I would chime in, that one of the reasons you get the invalid message is that Patreon invalidates your API credentials if you use the Patreon login API with your creator account.
