### ISSUE TITLE
Creator Access Tokens

### ISSUE THREAD

**Issue by tjdraper** [Patreon/patreon-php#26]
I’m working on a website that has multiple environments:

1. Production
2. Staging
3. Any number of local development environments on a developer's computer

Creator access/refresh tokens need to be refreshed when they expire. The problem is, this invalidates the old tokens. This means that if any one of these separate and distinct environments refreshes the tokens, the tokens the other environments were using become invalid. Clearly this is a major problem because a developer working on the API an application could cause a refresh to happen in their local development environment which would completely bork production. Or production could hose staging or local dev, which would cause staging or local to refresh the tokens, hence borking production again.

Is there any way around this madness?

**Comment by azmia** [comment]
Creator access tokens

**Comment by luceos** [comment]
Why don't you create a client per environment?

**Comment by tjdraper** [comment]
This is not a solution to this problem if for no other reason than "Any number of local development environments on a developer's computer".

**Comment by luceos** [comment]
As a developer you're supposed to create your own credentials. Credentials should never be valid across environments. Don't tell me you've never seen this: https://www.reddit.com/r/cscareerquestions/comments/6ez8ag/accidentally_destroyed_production_database_on/

**Comment by tjdraper** [comment]
As a matter of fact we do use a different environment for staging and local dev than we do for production, I was just trying to simplify the issue here. The issue remains.

**Comment by luceos** [comment]
You're missing the point of the article shared. The article mentions using production credentials inside a development environment causing a production database to be truncated.

An alternative solution here (as the patreon api isn't that extensive) is to simply mock it.

Anyway, good luck! And apologies for reviving this.
