### ISSUE TITLE
Missing code parameter although code is send

### ISSUE THREAD

**Issue by rummens** [Patreon/patreon-php#27]
Hi there,
I want to build the "Log in with Patreon Button" for my website but have an issue an step 3 of the OAuth Process. I am able to retrieve the one time use code but I'm not able to get the data of the user. 

I tried different post command, with and without curl and different encoding methods but I always get an 400 response with either: 

> Array ( [error] => invalid_request [error_description] => Missing code parameter. )

or 
> Array ( [error] => invalid_request [error_description] => not_supported_grant. )

The obvious thing is, that the code or the grant is not send but it is. Here is the encoded body of my POST request: 

`grant_type=authorization_code&code=fQEdzUJRcrZrbZqLKBryxXh9BYLMFK&client_id=XXXXXXX&client_secret=XXXXXX&redirect_uri=http%3A%2F%2Fcharger-companion.com%2Fpatreon-authorization%2F`

I tried to decode the redirect url, removed all access restriction from the server, escaped everything and used different Header to describe the type of decoding.

Here is the very frustrating thing: It works from my local server or my MacBook. If I send the exact request with Postman everything is fine. Also other APIs are working fine on my website, I have a few of them running. I am using a Wordpress installation, if that info can help.  

The error happens in the `private function __update_token($params)` function. 

Any ideas what could get wrong, somehow the code must get lost along the way :-) ?

Thanks
Marcel

**Comment by rummens** [comment]
I checked by sending the request to a service, which return the received data. Here is the output, the code is sent:

`{ "args": {}, "data": "", "files": {}, "form": { "amp;client_id": "XXX", "amp;client_secret": "XXX", "amp;code": "S0nStBJWE27finVIkjWY50M3jUFCVw", "amp;redirect_uri": "http://charger-companion.com/patreon-authorization/", "grant_type": "authorization_code" }, "headers": { "Accept": "*/*", "Connection": "close", "Content-Length": "310", "Content-Type": "application/x-www-form-urlencoded", "Host": "httpbin.org" }, "json": null, "origin": "80.237.133.195", "url": "http://httpbin.org/post" }`

What else can the error message "Missing code parameter." mean?

**Comment by rummens** [comment]
I found the solution myself. The issue was as suggest the encoding of the request. A normal POST request is encoded in "application/x-www-form-urlencoded" (at least on my servers) but the API seems to not understand this. The encoding must be "multipart/form-data"

So here is my updated function __update_token:

```
private function __update_token($params) {
	//print_r($params); // for Debug
        
    $url = 'https://api.patreon.com/oauth2/token';
	$headers = array("Content-Type:multipart/form-data"); // cURL headers for right encoding. Import
	
    $ch = curl_init();
    
    $options = array(
        CURLOPT_URL => $url,
        CURLOPT_HEADER => false,	// true for Debug
        CURLOPT_POST => 1,
        CURLOPT_HTTPHEADER => $headers,
        CURLOPT_POSTFIELDS => $params,
        CURLOPT_RETURNTRANSFER => true
    ); // cURL options
    curl_setopt_array($ch, $options);

    
    $response = (curl_exec($ch));
    curl_close($curl);
        
    //print_r($response)  	//for debug
       
	return $response;
		
	}
```

Hope that can help someone.

**Comment by myCodebox** [comment]
Chang in `OAuth.php` the line 39 from
`curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($params));`
to
`curl_setopt($ch, CURLOPT_POSTFIELDS, http_build_query($params, '', '&', PHP_QUERY_RFC3986));`
and it works.
