### ISSUE TITLE
Functions to test the API

### ISSUE THREAD

**Issue by jamiemac262** [Patreon/patreon-php#28]
Can we have a way to test the API?

I'll give an example, I'm trying to automate a process where a user subscribes for a premium membership on my website. To test this, I need a pledge, Obviously I want to make sure this is working before anyone actually pledges. The only way I could see to do this was to publish my page, create a new patreon account, and pledge to myself from the new patreon account. It would be helpful to have buttons such as "create a test pledge" etc that can be used in testing the API.

**Comment by xazinji** [comment]
Sadly Patreon does not offer a sandbox similar to Paypal at the moment.

**Comment by talsraviv** [comment]
Sadly indeed. This is something we're actively thinking about how to do properly and in a long-term way. We hear this a lot, and we feel your pain!

**Comment by LiamDawe** [comment]
Any update on this? Seems V2 includes a lot of what was needed but it's an insane struggle to actually build a properly working webhook without being able to fire dummy events.
