### ISSUE TITLE
Question: Campaign ID

### ISSUE THREAD

**Issue by LeaderSoul** [Patreon/patreon-php#32]
Hello
I am new and I don't know how can I get with this my campaign id. I use a discord chat bot and there I can put patreon details as such access token and campaign id but I can't find campaign id. Probably this will show to me.
Can someone share a source with us who can't find the solution to this? Thank you. :)

UPDATE:
It's nothing. :P I used the example file and put campaign_id in echo. :)

**Comment by talsraviv** [comment]
We should figure out an easy way to surface this in product too! Good feedback.
