### ISSUE TITLE
How can I know if my patron wants to hide his pledges?

### ISSUE THREAD

**Issue by ffMathy** [Patreon/patreon-php#38]
I have a website which uses the API here: https://shapeshifter.software (try scrolling down a bit).

Now, one of my users has the "Do not show my pledges publically" turned on, but the API still reveals him as a patron. How can I detect if he has that setting on? I don't see an attribute on it, and I want to respect his privacy.

**Comment by spencerhandley** [comment]
Hey @ffMathy, by authing into your service, patrons are explicitly granting your application access to their pledge data. At the moment, pledge visibility settings describe a contract within the patreon domain, once they grant access to their pledge data to third parties, it is up to third parties to describe the privacy terms with the user. 

I just surfaced this question to the rest of the platform team and we will consider passing on the pledge visibility in future cuts of the API. 

For now, you might want to add a step to your authorization flow that asks the user if they would like to hide their pledge data in your application. 

Thanks again for reaching out!

**Comment by spencerhandley** [comment]
I hear what you're saying, I'll pass it onto the rest of the team.

**Comment by ffMathy** [comment]
Can you provide an ETA on when this will be finalized? Will it ever be finalized? Will I know when it will be part of the plan?
