### ISSUE TITLE
Request: use of fetchCampaign() endpoint.

### ISSUE THREAD

**Issue by pdscti** [Patreon/patreon-php#40]
I've used to example code to get campaign data from my Patreon account, and have received a Art4\JsonAPIClient\ResourceCollection of the following structure:

![screen shot 2018-05-30 at 13 46 13](https://user-images.githubusercontent.com/7011980/40721160-9ecc3aba-6410-11e8-8cce-22ef86f290f9.png)

The container contains a "data" key that has within it my campaign data as an array of ResourceItems, but calling ->has('data') on the resource collection element returns a FALSE, and trying ->get('data') errors as if the data was not there. I am doing something wrong?

**Comment by Art4** [comment]
Try `$campaign->has('0')`.

As I can see `$campaign` is a `ResourceCollection` which you can see as an indexed array representation.

For better debug I recommend to use  `$element->getKeys()` to list all possible keys on an element.

**Comment by pdscti** [comment]
That's got it cheers: I did use getKeys() to see what was in there, but got an array of 0 => 0, which I assumed represented an empty array rather than one key of 0. Thanks for your help.
