### ISSUE TITLE
Help with Rewards Data

### ISSUE THREAD

**Issue by pdscti** [Patreon/patreon-php#41]
In #23 I asked how to get the full data of rewards from the campaigns method: since the changes made to the API, I'm back to only being able to find a reward id and no additional data. I'm guessing it's something to do with

`if ($user->has('relationships.pledges')) {
    /*
     * To look up the full resource that the relationship is referencing,
     * we have extended [art4/json-api-client/ResourceIdentifier](https://github.com/Art4/json-api-client/blob/master/docs/objects-resource-identifier.md)
     * with the `->resolve` method.
     * You pass in the original response document, and you get back a full resource,
     * with attributes, relationships, etc.
     */
    $pledge = $user->relationship('pledges')->get(0)->resolve($user_response);
    // Can now check attributes, e.g. $pledge->attribute('amount_cents');
}
`
from the README, but the example code uses $user and $user_response variables that aren't defined in the example, and I can't find anything within the API return that is of the correct class to get passed to the ->resolve method without causing an error. Any chance you could point me in the right direction?

**Comment by jrsun** [comment]
Hi pdscti,

The thing that you need to resolve is the response from API methods such as `$api_client->fetch_campaign()` or `$api_client->fetch_user()`. You could probably also manually parse the response from those methods and pull out the `included`.

Best,
Jeffrey

**Comment by pdscti** [comment]
Hi @jrsun 

Think I've got it working now: thanks.
