### ISSUE TITLE
Install without composer? on Wpengine

### ISSUE THREAD

**Issue by awrebels** [Patreon/patreon-php#42]
Anyone know if there is a way to install this on wpengine. They don't allow composer however i've read (and attempted) to download the package and install directly. Keep getting a 500 error which may be my lack of understanding there.  

Trying to get most recent list of the patrons in a php/html file.

**Comment by nperickson** [comment]
Hey @awrebels - You may want to post this over on https://www.patreondevelopers.com/c/patreon-wordpress-plugin-support which is where our Wordpress dev team troubleshoots and assists with these types of issues.

**Comment by awrebels** [comment]
@nperickson great point. thanks for the heads up

**Comment by awrebels** [comment]
Actually a question. i got the example (patron-list.php) working - not entirely using wordpress but the could is technically on the wpengine install. However I noticed the api call take about 40-60 seconds to actually complete and the process ends up getting killed. Has anyone else experienced that with the example?
