### ISSUE TITLE
Find out when they last paid

### ISSUE THREAD

**Issue by LiamDawe** [Patreon/patreon-php#46]
One thing I can't actually find out how to do, is find out when they last paid?

Looking over the API, you can see what level they're pledging at, if they were declined and so on...but you can't actually find out when they last paid?

Am I missing something obvious here?

Looking [here](https://github.com/Patreon/patreon-php/issues/13#issuecomment-267688353) (2016!!) it was said that:

> does not support lifetime payments and current payment status

Honestly, that makes this less than useful. Is it really that difficult just to add something we can grab for the date of their last taken (successful) payment? It's an essential feature I'm seriously surprised isn't available in the API?

**Please add it in.**

It looks like I'm going to have to go back to parsing the CSV file from each month, by downloading it manually a few times a month (to account for declines that then got taken later), which is not ideal. Seems there's no way for us to grab that from the API either, making such a simple thing an incredibly manual process.

**Comment by nperickson** [comment]
Hey @LiamDawe,

More information about the last successful payment is in the works and something we're including in the next update to the API. We'll be including something along the lines of a `last_charge_date` and `last_charge_status` attribute.

In the current version, declined_since indicates the date of the most recent payment if it failed, or `null` if the most recent payment succeeded. A pledge with a non-null declined_since should be treated as invalid.

**Comment by LiamDawe** [comment]
@nperickson Glad to hear it's coming, any idea when that will be live?

The problem with the current data, is people who haven't even paid yet show up, so we need the last charge date and status to know if they've paid anything.

**Comment by LiamDawe** [comment]
Okay, so v2 of the API is now in Beta and it sounds like exactly what we need.

How do we go about using it with this code?

**Comment by nperickson** [comment]
Hey @LiamDawe, It's now live and you should be able to find all the docs on it here; https://docs.patreon.com/#apiv2-oauth

The two pieces I mentioned should be under /api/oauth2/v2/campaigns/{campaign_id}/members if I remember correctly.

**Comment by LiamDawe** [comment]
Sorry, should have been more clear.

What do I have to adjust in patreon-php to point to the new API?

**Comment by LiamDawe** [comment]
I assume it will be updated when v2 leaves beta?

**Comment by nperickson** [comment]
Yup! That's on our list of things to do now that v2 is in beta, getting all of the client libs updated to support v2 in time for a full release.

**Comment by LiamDawe** [comment]
May I ask what the progress on this is?

**Comment by sustained** [comment]
Also wondering about v2 support.

**Comment by LiamDawe** [comment]
Just here to ask what the way is to now get a list of all pledges and their levels with V2, as I see that's now on the master.

**Comment by LiamDawe** [comment]
My issue is the current examples only show the flow of doing a login, not of just hooking into the API to get overall patreon campaign details.

**Comment by lithium720** [comment]
> fetch_member_details should give you detail of that member if you feed the member id in.
@codebard

I made it to this point, but it doesn't include the full scope of data. Is there _another_ lookup that needs to occur after this step?
I am trying to just get a list of member EMail addresses from my campaign. Any advice?

**Comment by codebard** [comment]
To get email or other details you must include it in the scopes when you made the request for your token to API. If the token does not have those scopes, those info wont come.

**Comment by lithium720** [comment]
I see. How does one achieve this with fetch_member_details(), though?

**Comment by codebard** [comment]
This must be done at the stage where you are requesting tokens - much earlier than fetch_member_details() :

When using get_tokens() to request your tokens after a user has authorized your app, you must send scope params to the api while sending your auth code to get the tokens.

$tokens = $oauth_client->get_tokens( $authorization_code, YOUR_REDIRECT_URI, array( 'scopes' => 'w:identity.clients' ) );

This will give the relevant scopes to that particular token and that token will be able to request the information you need.

I randomly gave an example, that bit of code above may not exactly be accurate. However it demonstrates the idea. You can check the scopes at api documentation and pick the right scopes for your purpose.

https://docs.patreon.com/#scopes

**Comment by lithium720** [comment]
What you've described seems like it's an extra step outside of:

> in API.php, using fetch_campaigns to get your campaigns, and then feeding the campaign id you want to fetch_page_of_members_from_campaign should give you members.
fetch_member_details should give you detail of that member if you feed the member id in.

I have the following as indicated above:

```php
$access_token = "CREATOR TOKEN";
$api_client = new Patreon\API($access_token);
$campaign_id = $api_client->fetch_campaigns()["data"][0]["id"];
foreach ($api_client->fetch_page_of_members_from_campaign($campaign_id, 1)["data"] as $patron) {
	print_r($api_client->fetch_member_details($patron["id"]));
}
```

Note that I'm using the creator token. Does this mean I need to have users authorize my app and build a full account linking process just to get data to parse (emails, last payment, etc) from my own creator account. All of this information is already available to me on the Patreon relationship manager so I can manually apply rewards, I'm just trying to automate it.

**Comment by codebard** [comment]
You can try manually requesting...

https://www.patreon.com/api/oauth2/v2/members/MEMBER_ID_HERE?include=address,campaign,user,currently_entitled_tiers&fields%5Buser%5D=email,first_name,full_name,image_url,last_name,thumb_url

...to see if you will be able to get the email with your creator token.
