### ISSUE TITLE
Auth form in my Unity App

### ISSUE THREAD

**Issue by immeasurability** [Patreon/patreon-php#47]
Hi! my taget create form in my app on Unity, for get plaget info of auth user in my app

next logic:
1 - user open app
2 - in app auth form interface by login and password, how in online games
2.1 - or there is another way?
3 - from app form, send to patreon api login and pasword
4 - patreon api return info by auth user
5 - app check pleget info (0$ 1$ 5$ 10$ +++)
6 - if user pleget more then 0$ app enable plaget content

if this posible to do?
i have php sql hosting and can, crate my api on my hostig for redirect user data from my app form
but i cont find any api! for post login (email) and pasword (maybe it's done for safety)

but **how i can identify user info in my app?**

**Comment by nperickson** [comment]
Hey @immeasurability 

I'd recommend checking out our API v2 documentation here: https://docs.patreon.com/#get-api-oauth2-v2-members-id

The php client lib isn't updated for v2 yet, but after going through the Oauth flow you should be able to verify the authenticated users membership information via `currently_entitled_tiers` and `last_charge_status`. With that information you can grant access to the content based on whether or not it meets the tier and the status is paid.

**Comment by immeasurability** [comment]
and now i test by class OAuth in here source

```
$client_id = {Client ID}; 
$client_secret = {Client Secret}; 

$oauth_client = new OAuth($client_id, $client_secret);

$redirect_uri = "{http://my site url for get token}";

$tokens = $oauth_client->get_tokens($_GET['code'], $redirect_uri);
```

what i see? access_denied
how?

**Comment by immeasurability** [comment]
gg complete!
nice work guys(((

my problem was in redirect_uri
in patreon client url: {mysite}.com/
in my api i use: {mysite}.com/index.php

patreon api return error: invalid_grant or invalid_client

i test api of worldpres, this is bad((( patreon get all time DDOS
one time of butoon (login) calls 10 api to patreon.com

1 current_user/campaigns?include=creator (Unauthorized)
2 refresh_token (invalid_grant)
3 current_user/campaigns?include=creator (Unauthorized)
4 authorization_code (result ok)
5 current_user (result user data ok)
6 redirect to this again 
7 current_user/campaigns?include=creator (Unauthorized)
8 refresh_token (invalid_grant)
9 current_user/campaigns?include=creator (Unauthorized)
10 current_user (result user data ok)

nice work ;)
