### ISSUE TITLE
No License Information?

### ISSUE THREAD

**Issue by vikingjs** [Patreon/patreon-php#5]
I'm writing software that leverages this code, but without any license expressly given, I'm heading into potentially deep water. I haven't found any license information in headers or readme. My guess is that you don't want to limit developers, but by saying nothing you actually don't grant any license at all.

If you want to place no limits on developers, MIT or Apache might be the way to go.

**Comment by 21echoes** [comment]
We went with Apache 2.0. Thanks for bringing this up!
