### ISSUE TITLE
Link to documentation redirects to Patreon homepage

### ISSUE THREAD

**Issue by Supuhstar** [Patreon/patreon-php#6]
The link in the readme, [https://www.patreon.com/platform/documentation](https://www.patreon.com/platform/documentation), redirects to the Patreon homepage, [https://www.patreon.com/home](https://www.patreon.com/home).

**Comment by 21echoes** [comment]
As the readme says, you must click that link "while logged in as a Patreon creator"

**Comment by Supuhstar** [comment]
I see, I didn't think that was an important criterion. Perhaps instead of redirecting to the homepage, throw a 401?
