### ISSUE TITLE
Get if user is currently pledging to my patreon, and how much

### ISSUE THREAD

**Issue by EnterateNorte** [Patreon/patreon-php#66]
Hi

How can I get the user current pladges to my patreon? I been trying to find out how to do it... so, when the user logs in, I can provide diferent access to my site depending on if he is a patreon, and how many cents he is paying

Thanks!

**Comment by codebard** [comment]
https://github.com/Patreon/patreon-php/blob/master/examples/user_details_and_patronage.php

This example should help you.

currently_entitled_amount_cents would be the current patronage a user has. Historical pledge would be the lifetime patronage s/he paid. The rest of variables are self explanatory.
