### ISSUE TITLE
Supress the Support-Info Screen for supporters

### ISSUE THREAD

**Issue by trimchess** [Patreon/patreon-php#7]
A certain level of support should allow for getting rid of the screen. (Lets say the >= 5$ once)
![jantie](https://cloud.githubusercontent.com/assets/4084006/17050147/a0f002de-4ff1-11e6-9c47-0b648ae464df.JPG)

**Comment by 21echoes** [comment]
Sorry, @trimchess I don't know enough about how you've implemented your site to be of any help at this point. With specific code examples of what you've tried, I may be able to be of more assistance.
