### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by pdscti** [Patreon/patreon-php#72]
The latest version of this library is apparently 1.0.0 (mentioned in https://www.patreondevelopers.com/t/php-fetch-user-returns-http-403-when-logging-in-with-other-account/1850) but the last tagged release of this library is 0.3.1. As I install the library using composer, the only way I can get the latest code is to install the bare master branch, which means any future changes in the master branch could potentially destroy my code.

Could a new release of the latest code be tagged up to allow composer users (and others) to pin the library to a known working version?

**Comment by codebard** [comment]
We wouldnt be able to do that currently, due to the fact that 1.0.0 is not backwards compatible with earlier versions of the lib in composer. 

However when we are moving everyone to API v2, we will also update the composer package at the right time - preferably after somehow communicating the update to users of the lib and giving them ample time to upgrade or adjust their installations.

**Comment by pdscti** [comment]
I may be misunderstanding you, but composer pins everything to specific release versions. By making a tagged release you'd allow people to choose to use either the old version of the API or the new when installing through composer. The fact that v1.0.0 isn't backwards compatible won't affect people unless they specifically choose to update. However because there's no tagged release for the 1.0.0 version, composer users can't safely choose to use the latest code because we can't pin the version we use to anything but the bare master branch.

**Comment by codebard** [comment]
> unless they specifically choose to update

Yes, that is the main concern. We would prefer to make easier paths to upgrade possible after we are ready to move people to v2 en masse.

**Comment by pdscti** [comment]
OK, but that means I currently can't use the library: the 0.3.1 release has a bug in it that means it doesn't work for what I'm doing, but the v1.0.0 version that apparently works doesn't have a release and so I can't use it without running the risk of future changes getting pulled in by composer before I'm ready for them.

You're not making it easier for me to upgrade in the future: you're making it impossible for me to upgrade when I need to.

**Comment by codebard** [comment]
Is it not possible for you to maintain a clone of this lib via git for the time being?

**Comment by pdscti** [comment]
I don't really want to be maintaining a clone of the repo just because there's no tag for this latest release: I'm maintaining a Drupal module that uses the library, and if I do that any bugs with the library suddenly become my issue. I don't understand why you're reluctant to just tag for a release people are already being told to use, but I'll just not fix the bugs raised against my module until you do and mark this issue as the blocker. Cheers for your help.

**Comment by codebard** [comment]
There is no problem tagging a release at github at this moment - if this is going to solve your problem and help you maintain your local lib until we release at composer.

**Comment by pdscti** [comment]
It's fine: I give up. Tag v1.0.0 whenever you like: I surrender.
