### ISSUE TITLE
fetch_user returns  object instead of array 

### ISSUE THREAD

**Issue by danilluzin** [Patreon/patreon-php#73]
`fetch_user` returns `Art4\JsonApiClient\Document` object instead of array by default even if it is explicitly asked to return array:
` $api_client->api_return_format = 'array';`

example shown here: [https://github.com/Patreon/patreon-php/blob/master/examples/user_details_and_patronage.php](link) actually throws an exception:
`Exception has occurred.
Error: Cannot use object of type Art4\JsonApiClient\Document as array`

`$current_member = $api_client->fetch_user();`
`$email = $current_member['data']['attributes']['email']`

fails.

**Comment by danilluzin** [comment]
Ok i think i finally know what the problem is.

the package you get using composer `composer require patreon/patreon` is SEVERAL YEARS old :/ .

To solve this issue you must manually download src from git and include it your project. nice.

**Comment by codebard** [comment]
Yes currently packagist package and the github repo are not synced, the latter is the up to date one. So until we undertake upgrading all composer-using installations to v2 and sync them, cloning git repo is the way.
