### ISSUE TITLE
refresh_token useless because of caching.

### ISSUE THREAD

**Issue by danilluzin** [Patreon/patreon-php#75]
Hi!

So i found this annoying bug/feature in the API and that is caching.
Every time you use fetch_user (for example) the api first tries to see if the same request was already made.
```
if ( isset( self::$request_cache[$api_request_hash] ) ) {
	return self::$request_cache[$api_request_hash];		
}
```

That means however that if you have an access_token, but fail to get `fetch_user()` (because token is expired, invalid etc) and try to use `refresh_token` to get a new `access_token`, you will get **the same** response with the new access_token, that you got with the old(invalid) access_token.

That is because api only **checks hash** of the request **without the token.**

In my opinion api shouldn't cache requests by default or at least have an option to turn caching off. And should probably warn users in the readme about it. 

🙃😄

**Comment by danilluzin** [comment]
#71 also mentions that the caching is static.

**Comment by codebard** [comment]
Good catch. It should be better to leave out refresh token calls from caching or do it optional.

**Comment by codebard** [comment]
@danilluzin The below branch adds access token to cache hashes, as well as implementing a 'skip_read_from_cache' argument to skip reading from cache altogether.

https://github.com/codebard/patreon-php/tree/add_access_token_to_cache_hash

Tested, works. Please check it out and let me know if it works with your setup and resolves your issue.
