### ISSUE TITLE
Generating lists via the API.

### ISSUE THREAD

**Issue by Cat5TV** [Patreon/patreon-php#8]
Hi David,
Thank you for the code and the great support I see in other Issues here. I've read over the examples and am getting my head around the API... slowly. I think though that my use case is different than the intention of the API, so I'm wondering if it can do what I need?

By following [this post](https://github.com/Patreon/patreon-php/issues/2#issuecomment-225409318) I'm able to connect and get my own profile data, so I know I've at least done that much correctly.

It seems the system is more setup (at least, through the demos) to allow a logged-in Patron to see their own info, but not to generate lists of all supporters. Am I right in this?

What I am hoping to do however, is to be able to generate a list, on demand, of all Patrons currently supporting our project, along with the rewards they are subscribed to. 

My intention is to be able to automate some of the rewards process. For example, we have a points-based system on our web site. It's doesn't contain any monetary value or anything like that: it's just a fun way for our site users to "compete" for the top 10. So what I'd like is that on a weekly basis, our system can (eg., cronjob) connect to the Patreon API and add a select number of points to each Patron's account in our database by cross-referencing their email address + reward.

Similarly we have some rewards which require a Patron to be subscribed for a specific number of weeks. So being able to generate our own API-driven reports of which Patrons have been at which reward level for how many weeks would be invaluable to us, and would help us honor our Patron rewards in a more timely fashion (as it would be much more automated).

While I don't expect a bunch of "free support" for this great script, it'd really help if you could point me in the right direction. And while my use case is pretty unique, I wonder if others out there are hoping to be able to obtain the same data from the API (eg., to generate a list of supporters, for example).

Any help you're able and willing to share would be much appreciated!

Thank you,
Robbie Ferguson

**Comment by 21echoes** [comment]
> It seems the system is more setup (at least, through the demos) to allow a logged-in Patron to see their own info, but not to generate lists of all supporters. Am I right in this?
>
> What I am hoping to do however, is to be able to generate a list, on demand, of all Patrons currently supporting our project, along with the rewards they are subscribed to.

It does both! For patrons, it grants your client application a token that can be used to fetch their info. For you, you can just use your own token to fetch your patrons' info.

In the code below, just hard-code your own token into `$access_token`. You can find your access token here: https://www.patreon.com/platform/documentation/clients as "Creator's Access Token". If it's expired, use "Creator's Refesh Token" and the `$oauth_client->refresh_token` function.

```
<?php

require_once('vendor/patreon/patreon/src/patreon.php');

use Patreon\API;
use Patreon\OAuth;

$creator_id = null;     // Replace with your data
$access_token = null;     // Replace with your data

$api_client = new Patreon\API($access_token);

$campaign_response = $api_client->fetch_campaign();
$campaign_id = $campaign_response['data'][0]['id'];

$pledges_page = $api_client->fetch_page_of_pledges($campaign_id, 10);

// in $pledges_page, you have the pledges as an array under the 'data' key, which tell you:
//   - who is pledging (e.g. $pledges_page['data'][0]['relationships']['patron']['data'], and you can look up the user profile data in $pledges_page['included'] by matching on type and id)
//   - and how much they are pledging (e.g. $pledges_page['data'][0]['attributes']['amount_cents'])

?>
```

**Comment by 21echoes** [comment]
I hope this helped you out! If not, you can check out the more complete example https://github.com/Patreon/patreon-php/blob/master/examples/patron-list.php and open a new issue if you still have problems :D

**Comment by LeigerGaming** [comment]
Managed to get it working, but I had to force composer to use v0.3.1 rather than using the latest (v1.0.0), as the latest version doesn't seem to actually work? Either way, success!
