### ISSUE TITLE
API

### ISSUE THREAD

**Issue by relisiuol** [Patreon/patreon-php#81]
Hello,

I would like to suggest some changes to your API, because it's too much complicated, I think. Or maybe I missed something?

Eg: I have a website where users can buy and sell "Packages". I tried to add Patreon Services like this:
- Sellers can connect their Patreon account and allow their Patrons to access their "Packages", by linking "Packages" to a Patreon Tier.
- Buyers can sign in, using same Patreon Login proccess, to access "Packages" a Seller has linked to a Patreon Tier.

- I thought, I only need to have an access to these scopes: `identity`, `identity.memberships` & `campaigns` to be sure Buyer is allowed to download "Packages".
- But no, because identity.memberships and `api/oauth2/v2/identity?include=memberships` does not return Tier ID & Campaign ID.
- I decided to add another scope: `campaigns.members` but again that didn't worked because `/api/oauth2/v2/campaigns/{campaign_id}/members` does not return User ID.

My questions:
The only way to do that is to use webhooks or a cron task to get members ID?
I have a single Login Process, so "Buyers" will need to accept some useless scopes, like `w:campaigns.webhook` too?

Best regards,

**Comment by codebard** [comment]
You can check the library's examples and additionally the WordPress plugin to see what kind of scopes you may need for such an application:

https://github.com/Patreon/patreon-wordpress

WordPress plugin has ample code that not only uses a unified login/pledge flow (very useful) but also does many other things like syncing posts from Patreon. It also checks for various patronage situations ranging from monthly active pledge to historical pledge.
