### ISSUE TITLE
Pledge data is not showing up

### ISSUE THREAD

**Issue by hironozu** [Patreon/patreon-php#9]
Hi there, I have been coding to check if an authenticated user has pledged someone else's campaign.

I have created my user account at Patreon and have pledged someone else's campaign. And the email I got says it is going to start changing me from the 1st of next month.

If the situation is as above, does `GET https://api.patreon.com/oauth2/api/current_user` return which campaign I have pledged (I am asking because I don't see it)?

Do I have to wait until the 1st of next month or the endpoint does not actually return such an information regardless if I have started getting charged (Though, the documentation and other related pages say it does)?

I have enquired this to Patreon and thought I should confirm with you as well as they told me to have a look at [API Documentation](https://www.patreon.com/platform/documentation/api), but I have been stuck after I had a look at the documentation.

Kind Regards,

**Comment by 21echoes** [comment]
Hey Hironozu! When you read the API documentation, it should have explained that there are three API's available:
> Presently, there are three APIs available:
> 
> - Fetching a your own profile and campaign info
> - Paging through a list of pledges to you
> - Fetching a patron's profile info

The OAuth-based API is designed for fetching information about people pledging *to you*, not you pledging to other people. We could probably add that to the OAuth API, but no one's asked for it before, as most people know who they are pledging to and dont need it in API form.

In the meantime, you can always use your Patreon cookie to request `GET api.patreon.com/current_user`, which is how the site and apps get your info.

**Comment by hironozu** [comment]
OK, what I wanted to do was to let Patreon users to do login another site with Patreon User Account via Patreon API only if s/he has pledged a specific campaign of someone else.

I guess how we can do that, for now, would be to use one of the endpoints with creator's account to store all the user data who have pledged to the creator, and when one of them did login via Patreon API to the another site it checks if s/he is on the list and do things if s/he is?

**Comment by 21echoes** [comment]
The way to do that is laid out in detail here: https://www.patreon.com/platform/documentation/oauth

To be clear -- if you are doing this on behalf of "a specific campaign of someone else", you must have *that creator* make the API client and use that client ID and secret.

**Comment by hironozu** [comment]
OK. Thank you for help.
